[build]
  functions = "netlify/functions"
  publish = "dist"

[dev]
  framework = "vite"
  targetPort = 5173
  port = 8888
  command = "npm run dev:frontend"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200